# Generated by Django 4.2.7 on 2023-11-07 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buynow_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='Description',
            new_name='description',
        ),
    ]
